[package]
name = "rs-flasher"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true

[[bin]]
name = "rs-flasher"
path = "./src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
espflash = { version = "3.0.0", default-features = false, features = ["serialport"] }
miette = { version = "7.2.0", features = ["fancy"] }
log = "0.4.21"
serde = "1.0.199"
serde_json = "1.0.116"
chrono = "0.4.38"
dialoguer = "0.11.0"
ctrlc = "3.4.4"
serialport = "4.3.0"
indicatif = "0.17.8"
env_logger = "0.11.3"
