[package]
name = "rs-flasher"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true

[[bin]]
name = "rs-flasher"
path = "./src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
espflash = { version = "3.2.0", default-features = false, features = ["serialport"] }
miette = { version = "7.4.0", features = ["fancy"] }
log = "0.4.22"
serde = "1.0.216"
serde_json = "1.0.133"
chrono = "0.4.39"
dialoguer = "0.11.0"
ctrlc = "3.4.5"
serialport = "4.6.1"
indicatif = "0.17.9"
env_logger = "0.11.5"
include-bytes-zstd = "0.1.0"
csv = "1.3.1"