name: PlatformIO CI

permissions:
  contents: write

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: cd Firmware && pio run -e esp32dev

      - name: Build LightFS
        run: cd Firmware && pio run -e fsbuild
      - name: Rename artifact
        run: |
          find . | grep bin
          ls -la
          ls -la Firmware
          ls -la Firmware/.pio
          ls -la Firmware/.pio/build
          ls -la Firmware/.pio/build/esp32dev
          ls -la Firmware/.pio/build/fsbuild

          cp Firmware/.pio/build/esp32dev/firmware.bin firmware.bin
          cp Firmware/.pio/build/fsbuild/littlefs.bin littlefs.bin
      - name: Archive Firmware Files
        uses: actions/upload-artifact@v3
        with: 
          name: firmware
          path: |
            firmware.bin
            littlefs.bin

  release:
    needs: build
    runs-on: ubuntu-latest
    environment: 
      name: github-releases
    steps:
    - name: Download Firmware Files
      uses: actions/download-artifact@v2
      with:
        path: release
    - name: Release Firmware
      uses: ncipollo/release-action@v1
      with:
        artifacts: release/*.bin
        generateReleaseNotes: true
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}